FROM alpine:3.17

LABEL author="Yongjie Zhuang"
LABEL descrption="Document Indexer"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk --no-cache add tzdata

WORKDIR /usr/src/

# binary is pre-compiled
COPY docindexer_build ./app_docindexer

ENV TZ=Asia/Shanghai

CMD ["./app_docindexer", "configFile=/usr/src/config/conf.yml"]
