mode.production: true

app.name: "docindexer"

mysql:
  enabled: true
  user: "${mysqlusername}"
  password: "${mysqlpassword}"
  database: "${app.name}"
  host: "${mysqladdr}"
  port: 3306

redis:
  enabled: true
  address: "redis"
  port: 6379
  username:
  password:
  database: 0

rabbitmq:
  enabled: true
  host: "rabbitmq"
  port: 5672
  username: "${rabbitmqusername}"
  password: "${rabbitmqpassword}"
  vhost: "/"

server:
  host: "0.0.0.0"
  port: 8091
  gracefulShutdownTimeSec: 5
  perf.enabled: false

consul:
  enabled: true
  consulAddress: consul:8500

logging.rolling.file: "/usr/src/logs/${app.name}.log"